name: GitHub Actions Pipeline
run-name: $${{ github.actor }} is running GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copy package meta info to root
      run: cp .github/actions/semantic-release/package-lock.json .

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: npm

    - name: Semantic Release
      if: "!contains(github.event.head_commit.message, '[skip release]')"
      run: |
        npm install @semantic-release/git@10.0.1 @semantic-release/changelog@6.0.3 -D
        npx -y semantic-release@21.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Move package meta info to .github/actions
      run: mv ./package* .github/actions/
